# Generated by Django 5.0 on 2023-12-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='planet',
            name='discovery_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planets.facility', to_field='name'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='hostname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planets.hostname', to_field='name'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='discovery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planets.method', to_field='name'),
        ),
    ]
